version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 7777:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  front:
    build:
      context: ..
      dockerfile: client/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 8890:8890
  back:
    build:
      context: ..
      dockerfile: server/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 1574:1574
    depends_on:
      - db


volumes:
  pgdata:
