version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: matcha
    ports:
      - 7777:7777
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
